### ISSUE TITLE
[BUG] Post titles not appearing in comments on profile page

### ISSUE THREAD

**Issue by noClaps** [discuitnet/discuit#91]
<img width="603" alt="image" src="https://github.com/discuitnet/discuit/assets/103803129/bbe376a9-240c-497b-bccf-685a0dfb6278">

The text at the top should say `@noClaps commented on “It is what it is” in Selfposting 3 hours ago.`

[Originally reported by HamboneDK.](https://discuit.net/DiscuitMeta/post/PfY67Ogh)

**Comment by previnder** [comment]
Fixed in [da471f3](https://github.com/discuitnet/discuit/commit/da471f3de75486f389af8c8e48a5aef40c80b6c3).

**Comment by noClaps** [comment]
<img width="597" alt="image" src="https://github.com/discuitnet/discuit/assets/103803129/94939f04-968c-47c8-9e7b-29da9f8eb123">

It's still not entirely fixed, titles don't show up for some comments. For others, they show up fine.
